# frozen_string_literal: true

require 'yard'

# This spec audits documentation across the whole codebase rather than a single
# class, so it doesn't fit RSpec/DescribeClass; and the YARD registry only
# needs building once for the whole file, so before(:context) is intentional.
# rubocop:disable-next RSpec/DescribeClass, RSpec/BeforeAfterAll
RSpec.describe 'YARD documentation coverage' do
  before(:context) do
    Dir.chdir(File.expand_path('../..', __dir__)) do
      YARD::Registry.clear
      YARD::Registry.load(Dir.glob('lib/**/*.rb'), true)
    end
  end

  # Class/module methods generated by Struct.new/Data.define blocks aren't real
  # def-with-params methods YARD can param-check, and initializers YARD infers
  # from `attr_*` don't carry an explicit signature either.
  def public_methods
    YARD::Registry.all(:method).select do |meth|
      meth.visibility == :public && !meth.is_alias? && meth.file.start_with?('lib/thingie')
    end
  end

  it 'documents every public method with a docstring' do
    undocumented = public_methods.reject { |meth| meth.docstring && !meth.docstring.empty? }

    expect(undocumented).to be_empty, lambda {
      undocumented.map { |meth| "#{meth.file}:#{meth.line} #{meth.path}" }.join("\n")
    }
  end

  it 'keeps @param tags in sync with each method signature' do
    mismatched = public_methods.filter_map do |meth|
      next if meth.tags(:param).empty? && meth.parameters.empty?

      documented = meth.tags(:param).map(&:name)
      actual = meth.parameters.map { |name, _default| name.to_s.delete('&*:').chomp(':') }
      next if documented.sort == actual.sort

      "#{meth.file}:#{meth.line} #{meth.path} (documented: #{documented}, actual: #{actual})"
    end

    expect(mismatched).to be_empty, -> { mismatched.join("\n") }
  end
end
